server:
  port: 8084

spring:
  application:
    name: internet-banking-fund-transfer-service
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://${REGISTRY_HOST}:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: ${REGISTRY_HOST}
    prefer-ip-address: true
