server:
  port: 8084

spring:
  application:
    name: internet-banking-fund-transfer-service
  datasource:
    url: jdbc:mysql://localhost:3309/core_bank
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    prefer-ip-address: true
